[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.2
  knolleary/PubSubClient @ ^2.8
  vshymanskyy/TinyGSM @ ^0.12.0

[env:esp32dev]
src_filter =
  +<main.cpp>
  -<mqtt_main.cpp>

[env:esp32dev-mqtt]
build_flags =
  -DTINY_GSM_MODEM_SIM7600
  -DTINY_GSM_RX_BUFFER=1024
  -DMODEM_BAUD=115200
  -DMODEM_RX_PIN=27
  -DMODEM_TX_PIN=26
  -DMODEM_PWRKEY_PIN=4
  -DMODEM_RESET_PIN=5
  -DMODEM_POWER_ON_PIN=23
  -DCELLULAR_APN=\"internet\"
  -DCELLULAR_USER=\"\"
  -DCELLULAR_PASS=\"\"
  -DMQTT_HOST=\"tcp.ap-southeast-1.clawcloudrun.com\"
  -DMQTT_PORT=39024
  -DMQTT_TOPIC=\"esp32/pasco\"
src_filter =
  -<main.cpp>
  +<mqtt_main.cpp>
